import argparse

parser = argparse.ArgumentParser()
parser.add_argument("input", help="Source image.")
parser.add_argument("--output", help="Output installer file.")
args = parser.parse_args()

if args.output is None:
    args.output = args.input.split('.')[0] + ".portrait.event"

def main():
    with open(args.output, "w") as file:
        label_basename = args.input.split('/')[-1].split(".")[0]
        file.write(f"//Generated by Portrait Installer Generator\n")
        file.write(f"\n")
        file.write(f"ALIGN 4\n")
        file.write(f"{label_basename}_Portrait:\n")
        file.write(f"#incbin \"{label_basename}_mug.dmp\"\n")
        file.write(f"\n")
        file.write(f"ALIGN 4\n")
        file.write(f"{label_basename}_Mini:\n")
        file.write(f"#incbin \"{label_basename}_minimug.dmp\"\n")
        file.write(f"\n")
        file.write(f"ALIGN 4\n")
        file.write(f"{label_basename}_Frames:\n")
        file.write(f"#incbin \"{label_basename}_frames.dmp\"\n")
        file.write(f"\n")
        file.write(f"ALIGN 4\n")
        file.write(f"{label_basename}_Palette:\n")
        file.write(f"#incbin \"{label_basename}_palette.dmp\"\n\n")
        file.write(f"setMugEntryDetailed({label_basename}PortraitID,{label_basename}_Portrait,{label_basename}_Frames,{label_basename}_Mini,{label_basename}_Palette,{label_basename}MouthX,{label_basename}MouthY,{label_basename}EyeX,{label_basename}EyeY)\n")

main()
